apiVersion: v1
kind: ConfigMap
metadata:
  name: env-configmap
data:
  # property-like keys; each key maps to a simple value
  POSTGRES_HOST: "eazismspro-dev-instance.ceq53sble10f.us-east-1.rds.amazonaws.com"
  POSTGRES_DB: "eazismspro"
  AWS_BUCKET: "eazismspro-dev"
  AWS_REGION: "us-east-1"
  AWS_PROFILE: "default"
  URL: "http://localhost:8100"
  JWT_SECRET: "testing"
